// packages/react/src/components/FlexBoard.tsx
import {
  useCallback,
  useLayoutEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import {
  calculateLayout,
  type LayoutNode,
  type PanelRect,
  type DropTarget,
} from "@flexboard/core";
import { useDividerResize } from "../hooks/useDividerResize.js";
import { usePanelDrag } from "../hooks/usePanelDrag.js";
import { DropPreview } from "./DropPreview.js";
import { useExternalPanelDrop } from "../hooks/useExternalPanelDrop.js";
import type { ExternalDropEvent } from "../types/events.js";
export interface FlexBoardRenderPanelProps {
  id: string;
}

export interface FlexBoardProps {
  layout: LayoutNode;

  onLayoutChange: (layout: LayoutNode) => void;

  renderPanel: (props: FlexBoardRenderPanelProps) => ReactNode;

  dividerSize?: number;
  minRatio?: number;
  maxRatio?: number;

  dragThreshold?: number;
  dropMargin?: number;
  dropSplitRatio?: number;

  externalDrop?: boolean;
  onExternalDrop?: (event: ExternalDropEvent) => void;

  className?: string;
  style?: CSSProperties;
}

export function FlexBoard({
  layout,
  onLayoutChange,
  renderPanel,

  dividerSize = 10,
  minRatio = 0.1,
  maxRatio = 0.9,

  dragThreshold = 5,
  dropMargin = 0,
  dropSplitRatio = 0.5,

  externalDrop = false,
  onExternalDrop,

  className,
  style,
}: FlexBoardProps) {
  // DOM
  const boardRef = useRef<HTMLDivElement>(null);
  // container size
  const [size, setSize] = useState<{
    width: number;
    height: number;
  } | null>(null);
  // ResizeObserver
  useLayoutEffect(() => {
    const element = boardRef.current;

    if (!element) {
      return;
    }

    const updateSize = () => {
      const rect = element.getBoundingClientRect();

      setSize({
        width: rect.width,
        height: rect.height,
      });
    };

    updateSize();

    const observer = new ResizeObserver(updateSize);

    observer.observe(element);

    return () => {
      observer.disconnect();
    };
  }, []);
  // core layout 계산
  const calculated =
    size && size.width > dividerSize && size.height > dividerSize
      ? calculateLayout(layout, size, dividerSize)
      : null;
  // divider hook
  const { startResize } = useDividerResize({
    layout,

    containerSize: size ?? {
      width: 0,
      height: 0,
    },

    dividerSize,
    minRatio,
    maxRatio,

    onLayoutChange,
  });
  // panel DnD hook
  const { isDragging, dropTarget, startDrag } = usePanelDrag({
    layout,
    boardElement: boardRef,

    panels: () => calculated?.panels ?? [],

    threshold: dragThreshold,
    margin: dropMargin,
    splitRatio: dropSplitRatio,

    onLayoutChange,
  });
  // 내부 Panel DnD
  const handleExternalDrop = useCallback(
    (target: DropTarget) => {
      onExternalDrop?.({
        targetId: target.targetId,
        direction: target.direction,
      });
    },
    [onExternalDrop],
  );
  // external DnD hook
  const {
    dropTarget: externalDropTarget,
    handleDragOver,
    handleDragLeave,
    handleDrop,
  } = useExternalPanelDrop({
    boardElement: boardRef,

    panels: () => calculated?.panels ?? [],

    enabled: externalDrop,

    margin: dropMargin,
    splitRatio: dropSplitRatio,

    onDrop: handleExternalDrop,
  });

  // render
  return (
    <div
      ref={boardRef}
      className={["flexboard", className].filter(Boolean).join(" ")}
      style={style}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      {calculated?.panels.map((panel: PanelRect) => (
        <div
          key={panel.id}
          className="flexboard__panel"
          style={{
            position: "absolute",
            left: panel.left,
            top: panel.top,
            width: panel.width,
            height: panel.height,
          }}
          onPointerDown={(event) => startDrag(panel.id, event)}
        >
          {renderPanel({
            id: panel.id,
          })}
        </div>
      ))}

      {calculated?.dividers.map((divider) => (
        <div
          key={divider.id}
          className={[
            "flexboard__divider",
            `flexboard__divider--${divider.orientation.toLowerCase()}`,
          ].join(" ")}
          style={{
            position: "absolute",
            left: divider.left,
            top: divider.top,
            width: divider.width,
            height: divider.height,
          }}
          onPointerDown={(event) => {
            event.stopPropagation();
            startResize(divider.id, divider.orientation, event);
          }}
        />
      ))}
      {dropTarget && <DropPreview rect={dropTarget.preview} />}
      {externalDropTarget && <DropPreview rect={externalDropTarget.preview} />}
    </div>
  );
}

// packages/vue/src/components/FlexBoard.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, shallowRef } from "vue";
import { calculateLayout, type LayoutNode, type Size } from "@flexboard/core";
import { useDividerResize } from "../composables/useDividerResize.js";
import DropPreview from "./DropPreview.vue";
import { usePanelDrag } from "../composables/usePanelDrag.js";
import { useExternalPanelDrop } from "../composables/useExternalPanelDrop.js";
import type { ExternalDropEvent } from "../types/events.js";
const props = withDefaults(
  defineProps<{
    layout: LayoutNode;

    dividerSize?: number;
    minRatio?: number;
    maxRatio?: number;

    dragThreshold?: number;
    dropMargin?: number;
    dropSplitRatio?: number;

    externalDrop?: boolean;
  }>(),
  {
    dividerSize: 10,
    minRatio: 0.1,
    maxRatio: 0.9,

    dragThreshold: 5,
    dropMargin: 0,
    dropSplitRatio: 0.5,

    externalDrop: false,
  },
);
const emit = defineEmits<{
  "update:layout": [layout: LayoutNode];
  "external-drop": [event: ExternalDropEvent];
}>();
const boardRef = ref<HTMLElement | null>(null);

const boardSize = ref<Size>({
  width: 0,
  height: 0,
});

const resizeObserver = shallowRef<ResizeObserver | null>(null);

const { startResize } = useDividerResize({
  layout: () => props.layout,
  boardSize,
  dividerSize: props.dividerSize,
  minRatio: props.minRatio,
  maxRatio: props.maxRatio,

  onUpdate: (layout) => {
    emit("update:layout", layout);
  },
});
const {
  dropTarget: externalDropTarget,
  isExternalDragging,
  handleDragOver,
  handleDragLeave,
  handleDrop,
} = useExternalPanelDrop({
  boardElement: boardRef,

  panels: () => calculatedLayout.value.panels,

  enabled: () => props.externalDrop,

  margin: props.dropMargin,
  splitRatio: props.dropSplitRatio,

  onDrop: (target) => {
    emit("external-drop", {
      targetId: target.targetId,
      direction: target.direction,
    });
  },
});
/**
 * 현재 보드 크기를 기준으로
 * Core에서 실제 패널 / divider 좌표를 계산한다.
 */
const calculatedLayout = computed(() => {
  if (boardSize.value.width <= 0 || boardSize.value.height <= 0) {
    return {
      panels: [],
      dividers: [],
    };
  }

  return calculateLayout(props.layout, boardSize.value, props.dividerSize);
});

const { isDragging, dropTarget, startDrag } = usePanelDrag({
  boardElement: boardRef,
  layout: () => props.layout,
  panels: () => calculatedLayout.value.panels,

  threshold: props.dragThreshold,
  margin: props.dropMargin,
  splitRatio: props.dropSplitRatio,

  onUpdate: (layout) => {
    emit("update:layout", layout);
  },
});

onMounted(() => {
  if (!boardRef.value) {
    return;
  }

  resizeObserver.value = new ResizeObserver(([entry]) => {
    if (!entry) {
      return;
    }

    boardSize.value = {
      width: entry.contentRect.width,
      height: entry.contentRect.height,
    };
  });

  resizeObserver.value.observe(boardRef.value);
});

onBeforeUnmount(() => {
  resizeObserver.value?.disconnect();
});
</script>

<template>
  <div
    ref="boardRef"
    class="flexboard"
    @dragover="handleDragOver"
    @dragleave="handleDragLeave"
    @drop="handleDrop"
  >
    <div
      v-for="panel in calculatedLayout.panels"
      :key="panel.id"
      class="flexboard__panel"
      :style="{
        top: `${panel.top}px`,
        left: `${panel.left}px`,
        width: `${panel.width}px`,
        height: `${panel.height}px`,
      }"
      @pointerdown="startDrag(panel.id, $event)"
    >
      <slot name="panel" :id="panel.id" :rect="panel" />
    </div>

    <div
      v-for="divider in calculatedLayout.dividers"
      :key="divider.id"
      class="flexboard__divider"
      :class="{
        'flexboard__divider--horizontal': divider.orientation === 'H',
        'flexboard__divider--vertical': divider.orientation === 'V',
      }"
      :style="{
        top: `${divider.top}px`,
        left: `${divider.left}px`,
        width: `${divider.width}px`,
        height: `${divider.height}px`,
      }"
      @pointerdown="startResize(divider, $event)"
    />
    <!-- 내부 패널 DnD preview -->
    <DropPreview v-if="dropTarget" :rect="dropTarget.preview" />
    <!-- 외부 → FlexBoard DnD preview -->
    <DropPreview v-if="externalDropTarget" :rect="externalDropTarget.preview" />
  </div>
</template>

<style scoped>
.flexboard {
  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
}

.flexboard__panel {
  position: absolute;
  overflow: hidden;
  touch-action: none;
}

.flexboard__divider {
  position: absolute;
  touch-action: none;
  user-select: none;
}

.flexboard__divider--horizontal {
  cursor: col-resize;
}

.flexboard__divider--vertical {
  cursor: row-resize;
}
</style>
